-- Active: 1716820982810@@127.0.0.1@3306
INSERT INTO "group" ("name", "company") VALUES
('TWICE', 'JYP'),
('BLACKPINK', 'YG Entertainment'),
('Red Velvet', 'SM Entertainment'),
('ITZY', 'JYP'),
('G-IDLE', 'Cube Entertainment'),
('GFRIEND', 'Source Music');

INSERT INTO "idol" ("stage_name", "real_name", "group_id") VALUES
('Nayeon', 'Im Nayeon', 1),
('Jeongyeon', 'Yoo Jeongyeon', 1),
('Momo', 'Hirai Momo', 1),
('Sana', 'Minatozaki Sana', 1),
('Jihyo', 'Park Jihyo', 1),
('Mina', 'Myoui Mina', 1),
('Dahyun', 'Kim Dahyun', 1),
('Chaeyoung', 'Son Chaeyoung', 1),
('Tzuyu', 'Chou Tzuyu', 1),
('Jisoo', 'Kim Jisoo', 2),
('Jennie', 'Kim Jennie', 2),
('Rosé', 'Park Chaeyoung', 2),
('Lisa', 'Lalisa Manoban', 2),
('Irene', 'Bae Joohyun', 3),
('Seulgi', 'Kang Seulgi', 3),
('Wendy', 'Son Seungwan', 3),
('Joy', 'Park Sooyoung', 3),
('Yeri', 'Kim Yerim', 3),
('Yeji', 'Hwang Yeji', 4),
('Lia', 'Choi Jisu', 4),
('Ryujin', 'Shin Ryujin', 4),
('Chaeryeong', 'Lee Chaeryeong', 4),
('Yuna', 'Shin Yuna', 4),
('Soyeon', 'Jeon Soyeon', 5),
('Miyeon', 'Cho Miyeon', 5),
('Minnie', 'Nicha Yontararak', 5),
('Soojin', 'Seo Soojin', 5),
('Yuqi', 'Song Yuqi', 5),
('Shuhua', 'Yeh Shuhua', 5),
('Sowon', 'Kim Sojung', 6),
('Yerin', 'Jung Yerin', 6),
('Eunha', 'Jung Eunbi', 6),
('Yuju', 'Choi Yuna', 6),
('SinB', 'Hwang Eunbi', 6),
('Umji', 'Kim Yewon', 6);
